### ISSUE TITLE
Java client java.lang.AssertionError: assertion failed: No plan for Relation

### ISSUE THREAD

**Issue by men348** [pingcap/tispark#848] opened 2019-06-20 10:27 UTC
Tidb have published the version of 2.1.12 in seven days ago (2019-06-13). I tried to read data from instances of that version  by tispark java client which version is 2.1-spark_2.4. But I failed.  My spark version is 2.4.3.  
Errors like this:  Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.AssertionError: assertion failed: No plan for Relation[xxx,xxxx]).
I need you help.

**Comment by birdstorm** [comment] 2019-06-20 11:03
Sure, I will update as soon as I reproduce your error.

**Comment by birdstorm** [comment] 2019-06-20 11:15
I will close this issue because it duplicates with #849

**Closed by birdstorm** 2019-06-20 11:15 UTC
Labels: duplicate
