### ISSUE TITLE
[BUG] Meet "object Predef does not have a member classOf" error when use tispark in Livy

### ISSUE THREAD

**Issue by yantzu** [pingcap/tispark#1076] opened 2019-08-29 01:02 UTC
**Describe the bug**
When use tispark in livy thrift server, I add tispark jar with livy.session.conf.spark.jars config properties. The spark application will start, but will be dead soon.

**What did you do**
Just submit spark application using:
```
beeline -n hive -p -u "jdbc:hive2://localhost:10010" --hiveconf livy.session.conf.spark.sql.extensions=org.apache.spark.sql.TiExtensions --hiveconf livy.session.conf.spark.tispark.pd.addresses=localhost:2379 --hiveconf livy.session.conf.spark.jars=hdfs:///tispark-core-2.1.4-spark_2.4-jar-with-dependencies.jar
```
**What do you expect**
Spark application should start normally, and I can access tidb in spark

**What happens instead**
Spark application stopped with error:
```
scala.reflect.internal.FatalError: object Predef does not have a member classOf
	at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1182)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1199)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1234)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.Predef_classOf$lzycompute(Definitions.scala:1465)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.Predef_classOf(Definitions.scala:1465)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.isPredefClassOf(Definitions.scala:1455)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:4912)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdentOrWildcard$1(Typers.scala:4935)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5367)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5501)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5509)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5039)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5339)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5477)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:442)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:862)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:820)
	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:682)
	at org.apache.livy.repl.SparkInterpreter$$anonfun$bind$1.apply(SparkInterpreter.scala:132)
	at org.apache.livy.repl.SparkInterpreter$$anonfun$bind$1.apply(SparkInterpreter.scala:132)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:221)
	at org.apache.livy.repl.SparkInterpreter.bind(SparkInterpreter.scala:131)
	at org.apache.livy.repl.AbstractSparkInterpreter.postStart(AbstractSparkInterpreter.scala:72)
	at org.apache.livy.repl.SparkInterpreter$$anonfun$start$1.apply$mcV$sp(SparkInterpreter.scala:88)
	at org.apache.livy.repl.SparkInterpreter$$anonfun$start$1.apply(SparkInterpreter.scala:63)
	at org.apache.livy.repl.SparkInterpreter$$anonfun$start$1.apply(SparkInterpreter.scala:63)
	at org.apache.livy.repl.AbstractSparkInterpreter.restoreContextClassLoader(AbstractSparkInterpreter.scala:340)
	at org.apache.livy.repl.SparkInterpreter.start(SparkInterpreter.scala:63)
	at org.apache.livy.repl.Session$$anonfun$1.apply(Session.scala:128)
	at org.apache.livy.repl.Session$$anonfun$1.apply(Session.scala:122)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Screenshots**
 -->

**Spark and TiSpark version info**
Spark 2.4.0
TiSpark 2.1.4

**Additional context**
You may also provide TiDB version here if it is related to the issue.
-->

**Comment by yantzu** [comment] 2019-08-29 01:32
The reason is tispark include scala-lang class in assembly jar which is not compatible with livy. Remove scala-lang from assembly jar will fix this bug.

**Comment by zhexuany** [comment] 2019-08-29 03:27
@yantzu We already removed scala-lang in our master. You could clone the code and build a jar yourself.

**Comment by yantzu** [comment] 2019-08-29 03:29
That would be great!

**Comment by marsishandsome** [comment] 2019-08-29 03:36
@yantzu you can download latest tispark (master branch) from https://download.pingcap.org/tispark-assembly-latest-linux-amd64.tar.gz

**Comment by birdstorm** [comment] 2019-08-29 07:05
A known working solution:
> beeline -n hive -p -u "jdbc:hive2://localhost:10010" --hiveconf livy.session.conf.spark.sql.extensions=org.apache.spark.sql.TiExtensions --hiveconf livy.session.conf.spark.tispark.pd.addresses=localhost:2379 --hiveconf livy.session.conf.spark.jars=hdfs:///tispark-core-2.1.4-spark_2.4-jar-with-dependencies.jar

Under verification.

**Comment by yantzu** [comment] 2019-08-29 09:52
Thank you @marsishandsome , I have build my own version base on 2.1.4 code. I would appreciate if 2.1.5 could include this bug fix and release soon.

**Comment by marsishandsome** [comment] 2019-08-29 09:58
> Thank you @marsishandsome , I have build my own version base on 2.1.4 code. I would appreciate if 2.1.5 could include this bug fix and release soon.

2.1.5 will be released in next week. I will keep you posted.

**Comment by marsishandsome** [comment] 2019-09-02 06:20
hi @yantzu  tispark-2.1.5 is released, please download here https://github.com/pingcap/tispark/releases/tag/v2.1.5

**Comment by yantzu** [comment] 2019-09-02 09:01
Thanks a lot, I will have a try

**Comment by birdstorm** [comment] 2019-09-03 11:26
@yantzu Hi, if the problem is solved, you can close this issue;-) Thanks~

**Comment by yantzu** [comment] 2019-09-03 12:14
Closed. Thanks a lot!

**Closed** 2019-09-03 12:14 UTC
Labels: bug
